apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-crystal
  labels:
    app: demo-crystal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-crystal
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demo-crystal
    spec:
      containers:
        - image: brentley/ecsdemo-crystal:latest
          imagePullPolicy: Always
          name: demo-crystal
          ports:
            - containerPort: 3000
              protocol: TCP
