apiVersion: v2
name: cert-manager
description: A Helm chart for installing cert-manager
type: application
version: 0.0.1
appVersion: "1.0"
dependencies:
- name: cert-manager
  version: v1.11.0
  repository: https://charts.jetstack.io