apiVersion: v2
name: argo-rollouts
description: A Helm chart for Argo Rollouts
type: application
version: 0.0.1
appVersion: "1.0"
dependencies:
- name: argo-rollouts
  version: 2.22.3
  repository: https://argoproj.github.io/argo-helm
