apiVersion: v2
name: argo-workflows
description: A Helm chart for Argo Workflows
type: application
version: 0.0.1
appVersion: "1.0"
dependencies:
- name: argo-workflows
  version: 0.22.14
  repository: https://argoproj.github.io/argo-helm
